### ISSUE TITLE
DiscountCode validation endpoint

### ISSUE THREAD

**Issue by nocturne32** [fapi-cz/fapi-client#17]
To my knowledge, there is no easy way to validate discount codes with this endpoint: https://web.fapi.cz/api-doc/#api-DiscountCodes-IsValidDiscountCode

**Comment by slischka** [comment]
Hello, you mean that the endpoint IsValidDiscountCode missing ?

**Comment by nocturne32** [comment]
Yes, but I am not sure if that is intended though. The only actions available are find, findAll, create, update, delete.

**Comment by slischka** [comment]
No it is not intended :) I will try to add it today

**Comment by slischka** [comment]
new version released
